version: '3.8'
services:
  ### postgres database for inventory
  db-inventory:
    container_name: db-inventory
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_inventory
      MYSQL_USER: jtavarez
      MYSQL_PASSWORD: P@$$w0rd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306  # Cambié el puerto del contenedor a 3306 para que coincida con el puerto por defecto
    expose:
      - 3307  # Cambié el puerto expuesto a 5432 para que coincida con el puerto por defecto

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: jtavarez
      MYSQL_PASSWORD: P@$$w0rd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306  # Cambié el puerto del contenedor a 3306 para que coincida con el puerto por defecto
    expose:
      - 3308  # Cambié el puerto expuesto a 3306 para que coincida con el puerto por defecto

  db-products:
    container_name: db-products
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_products
      MYSQL_USER: jtavarez
      MYSQL_PASSWORD: P@$$w0rd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306  # Puerto del contenedor mapeado al puerto de host
    expose:
      - 3309  # Puerto expuesto